### ISSUE TITLE
stray lines causing failure in main file-read loop

### ISSUE THREAD

**Issue by arlin** [mengysun/AA_exchangeability#2]
We found that these lines are causing an error and can be commented out with no ill effect: 

```python
most_ties_number=pd.DataFrame(dms.DMS_score.value_counts()).reset_index()['index'][0]
dms['f_ties']=np.mean(dms['DMS_score']==most_ties_number)
```

Delete or comment out these lines every place that they occur (multiple files, some with multiple instances)

**Comment by mengysun** [comment]
Done
