### ISSUE TITLE
request for clarification on sym_sig and sig in FigS4 code

### ISSUE THREAD

**Issue by arlin** [mengysun/AA_exchangeability#3]
I’m getting a different value for ```1 - sym_sig/302```.  Mengyi’s value  of 0.006622 indicates sym_sig = 300, i.e., all are significantly non-symmetric but 2.  But I’m getting sym_sig = 302.  

I don’t understand why the conditionals used to count this are different here than in Fig. 2.  The code here is using ```if (pi*361)<=0.05``` and ``if (i!=18) and (p_sym*153<=0.05)```.  In the Fig 2 code, the corresponding scalars are 380 and 190 and there is no exclusion of index value 18. I understand the choices for the Fig 2 values. I don’t understand the ones for S4. I think this warrants an explanation in the code.

**Comment by mengysun** [comment]
Somehow in the Protein ddG data set used in S4, there are no data for mutational effects from Cysteine to all other amino-acids. Therefore there are only 20*19-19=361 panels. In addition, for testing symmetries, we can only conduct (380-38)/2=171 tests. I probably need to fix the 153 to 171. Let me check the code first.

**Comment by mengysun** [comment]
Just fixed the number
